// This file is created by the build system and should not be manually edited or changes
// will be lost.

// It contains all the user facing text content translated into all the supported languages.
// Therefore App components only need to be passed a language and this text data object 
// via props to be able to render themselves in the user selected language. Components should only use
// supported keys (which are automatically generated for code completion) and therefore do not
// need to have knowledge of any part of the text content and any typos or missing keys will
// be found at build time.

export default {
    "cymraeg": {
        "pageTitleKeyHome": "Hafan",
        "pageTitleKeyMap": "Map",
        "pageTitleKeyVocabulary": "Geirfa",
        "pageTitleKeyAbout": "Amdanom",
        "pageTitleKeySubmit": "Cyflwyno",
        "pageTitleKeyPrivacy": "Preifatrwydd",
        "pageTitleTagKeyHome": "BYW | Hafan",
        "pageTitleTagKeyMap": "BYW | Map",
        "pageTitleTagKeyVocabulary": "BYW | Geirfa",
        "pageTitleTagKeyAbout": "BYW | Amdanom",
        "pageTitleTagKeySubmit": "BYW | Cyflwyno",
        "pageTitleTagKeyPrivacy": "BYW | Preifatrwydd",
        "pageTitleTagKey404": "BYW | Heb ei Ddarganfod",
        "footerTest404": "Profwch y dudalen 404",
        "footerContributing": "Cyfrannu",
        "footerP1": "Gall pawb helpu dysgwyr i ddod o hyd i leoedd i fynd a defnyddio eu Cymraeg. Mae eich cyflwyniadau hefyd yn ein helpu i fonitro faint mae'r iaith yn cael ei defnyddio, nid yn unig yng Nghymru, ond ledled y byd",
        "footerP2": "Mae cyflwyno adolygiad yn gyflym ac nid oes angen cyfrif na mewngofnodi. Os ydych chi'n ymwybodol o le y gellir clywed a defnyddio Cymraeg, ond nad yw eisoes yn ein mynegai, bydd ei gyflwyno i'r mynegai yn rhoi gwybod i eraill",
        "footerUsefulLinks": "Dolenni defnyddiol",
        "footerVisitOn": "Ymwelwch â ni ar",
        "category0": "Hynod annhebygol",
        "category1": "Ddim yn debygol iawn",
        "category2": "Tebygol",
        "category3": "Tebygol iawn",
        "category4": "Hynod debygol",
        "category5": "Yn bendant",
        "show": "Gweld",
        "categorise": "Categoreiddio",
        "notFoundTitle": "Heb ei Ddarganfod",
        "homeCrowdSourced": "Torf o ffynonellau",
        "homeWelsh": "Cymraeg",
        "homeLanguageResource": "adnodd iaith",
        "homeLets": "Gadewch i ni",
        "homeFind": "ffeindio",
        "homeSomewhere": "rhywle",
        "homeHeroTitle": "Darganfyddwch ble i ddefnyddio a chlywed yr iaith",
        "homeSearch": "Chwilio",
        "homeSearchPlaceholder": "Beth ydych chi'n chwilio amdano",
        "homeSearchResults": "Canlyniadau Chwilio",
        "homeLocationPlaceholder": "Lleoliad",
        "homeAnd": "a",
        "homeMore": "mwy",
        "homeApi": "API",
        "homeMap": "Map",
        "homeLanguages": "Ieithoedd",
        "homeLanguageChoose": "Dewiswch eich dewis iaith",
        "homeServicesSectionTitle": "Ein Gwasanaethau",
        "homeServicesSectionTitle1": "Beth mae'n",
        "homeServicesSectionTitle2": "wneud i mi",
        "homeServices1Title": "Lleoedd Lleol",
        "homeServices1Desc": "Mae'r wefan hon yn ymwneud yn syml â chael pobl i ddefnyddio eu Cymraeg. Mae ar gael mewn cwpl o ieithoedd i helpu dysgwyr o bob rhan o'r byd i ddod o hyd i leoedd i ddefnyddio a gwella eu sgiliau Cymraeg",
        "homeServices2Title": "Siaradwyr Brodorol",
        "homeServices2Desc": "Fodd bynnag, nid yw hyn yn ymwneud â dysgwyr yn unig. Mae angen i'r rheini sy'n rhugl hefyd ddefnyddio eu Cymraeg pryd bynnag y gallant. Mae angen clywed Cymraeg ar y stryd, yn y siopau a ble bynnag rydyn ni'n dod at ein gilydd",
        "homeServices3Title": "Diwrnodau allan",
        "homeServices3Desc": "Felly, cyn i chi siopa, ewch ar ddiwrnod allan, neu beth bynnag yr ydych chi'n hoffi ei wneud, gweld a fydd croeso i'r Gymraeg ac, yn anad dim, defnyddiwch eich Cymraeg eich hun!",
        "homeThoughtOfTheDay": "Meddwl y dydd",
        "mapResult": "Canlyniad",
        "mapResults": "Canlyniadau",
        "mapPages": "Tudalennau",
        "mapSearchPlaceholder": "Chwilio am leoedd, cyfesurynnau a chodau post",
        "mapLegendTitle": "Chwedl i'r map",
        "mapLegendSubheading": "Cipolwg cyflym ar debygrwydd siarad Cymraeg",
        "vocabTitle": "Geirfa",
        "vocabBeta": "Beta",
        "vocabP1": "Mae hwn yn fersiwn beta o ymgais i ddarparu adnodd chwiliadwy ar gyfer dywediadau a glywir yn gyffredin",
        "vocabP2": "Ar hyn o bryd mae ganddo",
        "vocabP3": "gair ac ymadrodd allan o darged o",
        "vocabResultsFound": "ymadroddion a geiriau a ddarganfuwyd",
        "vocabEnglish": "Saesneg",
        "vocabCymraeg": "Cymraeg",
        "vocabNotes": "Nodiadau",
        "aboutTitle": "Amdanom ni",
        "aboutSub1": "Beth all",
        "aboutSub2": "wneud?",
        "aboutP1": "Mae Byw.cymru yn adnodd Cymraeg sy'n cael ei yrru gan y gymuned, o ffynonellau torf. Ei brif nod yw helpu dysgwyr ac eraill sydd â diddordeb yn yr iaith i ddod o hyd i leoedd lle gallant glywed a defnyddio'r iaith",
        "aboutP2a": "Mae'r prosiect cyfan yn",
        "aboutOpenSource": "ffynhonnell agor",
        "aboutP2b": "a gwneir pob penderfyniad yn yr awyr agored ar y prosiect repo, a gynhelir arno",
        "aboutP3": "Nod y prosiect yw ei gwneud hi'n hawdd darganfod y wybodaeth hon, gyda'r mwyaf o gyfranogiad cymunedol. Felly mae dyluniad y wefan i fod mor hawdd a chyflym â phosibl. Mae'n canolbwyntio ar dudalen y map, sef y prif adnodd ar gyfer chwilio'r mynegai",
        "aboutP4": "Mae'r holl god sy'n ffurfio'r wefan ar gael yn repo'r prosiect ac mae unrhyw un yn gallu ei weld. Mae'r wefan a'r data yn cael eu cynnal gan ddefnyddio adnoddau a roddir yn y gymuned. Mae'r Api yn darparu mynediad i'r data i unrhyw un sydd ei eisiau. Dros amser, disgwylir y bydd nifer y pwyntiau terfyn Api yn cynyddu i'w gwneud yn fwy defnyddiol i ddatblygwyr ac ymchwilwyr",
        "aboutContributing": "Cyfrannu",
        "aboutP5": "Y ffordd gyflymaf a hawsaf i gyfrannu at y prosiect yw cyflwyno adolygiad. Mae hyn yn golygu ychwanegu lle newydd i'r mynegai neu ddiweddaru un sy'n bodoli eisoes os oes angen",
        "aboutP6": "Gall unrhyw un wneud hyn ac nid oes angen mewngofnodi na chyfrif",
        "aboutP7a": "Os darganfyddir unrhyw broblemau, dod o hyd i chwilod neu awgrymiadau i'w gwneud, edrychwch ar y",
        "aboutP7b": "tudalen materion",
        "aboutP7c": "ar",
        "aboutP8": "Dylai'r rhai sy'n dymuno cymryd mwy o ran edrych ar repo'r prosiect, sy'n cael ei gynnal arno",
        "aboutP9": "Mae digon o waith i'w wneud i wneud y prosiect hwn yn offeryn defnyddiol i ddysgwyr Cymru",
        "submitTitle": "Cyflwyno categori",
        "submitName": "Enw",
        "submitCategory": "Categori",
        "submitStatus": "Statws",
        "howToTitle": "Sut i",
        "howToFind": "dewch o hyd i rywle sydd eisoes wedi'i restru",
        "howToOL1a": "Bydd yr adeilad a ddewisoch ar dudalen y map yn ymddangos yn y blwch cyflwyno yn barod ar gyfer eich adolygiad o debygolrwydd siarad Cymraeg",
        "howToOL1b": "Dewiswch yr hyn rydych chi'n teimlo sydd orau a tharo cyflwyno",
        "howToOL1c": "Os nad yw'r adeilad a ddewisoch lle rydych chi am gyflwyno adolygiad ar ei gyfer, yna llusgwch y pin map, bydd y ffurflen yn cael ei chlirio, a gallwch chi ddod o hyd i'r adeilad rydych chi am ei gyflwyno",
        "howToSubmit": "cyflwyno adeilad newydd",
        "howToOL2a": "Llusgwch y pin map i ddod o hyd i'r lle",
        "howToOL2b": "Bydd y cyfesurynnau a'r cod post yn cael eu llenwi. Ychwanegwch enw'r adeilad a'r cyfeiriad fel yr hoffech iddo ymddangos yn y mynegai",
        "howToOL2c": "Dewiswch pa mor debygol ydych chi'n teimlo bod rhywun o glywed a gallu defnyddio'r Gymraeg yn yr adeilad. Nid yw hyn yn wyddonol, dim ond yr hyn sy'n debygol yn eich barn chi",
        "howToInaccurate": "Os yw'r mynegai yn ymddangos yn anghywir",
        "howToP1": "Mae categori (pa mor debygol yw hi o ddefnyddio Cymraeg) adeilad yn cael ei gyfrif trwy gydgrynhoi'r holl adolygiadau a dderbyniwyd. Felly bydd eich cyflwyniad yn cael ei ystyried ar unwaith, ond gall effeithio ar y sgôr gyfredol neu beidio",
        "howToP2": "Os ydych chi'n teimlo bod sgôr adeilad yn bell i ffwrdd ac yn aros yn bell i ffwrdd ar ôl i chi gyflwyno'ch sgôr, yna cysylltwch â ni. Os mai chi yw perchennog y busnes gallwn ni helpu trwy eich cyfeirio chi i gyfeiriad adnoddau i helpu i gynyddu'r defnydd o'r Gymraeg yn eich busnes. Os yw'r data yn y mynegai yn hollol anghywir, yna gallwn ei gywiro",
        "formSubmitted": "Cyflwynwyd",
        "formSubmit": "Cyflwyno",
        "formClear": "Clirio",
        "formClearToDrop": "Cliriwch y ffurflen i ollwng pin",
        "formDragPin": "Llusgwch y pin ...",
        "formName": "Enw'r adeilad",
        "formAddress": "Cyfeiriad yr adeilad",
        "formPostcode": "Cod post yr adeilad",
        "formCoordinates": "Cyfesurynnau",
        "formCategory": "Categori",
        "errorMissingName": "Mae angen enw",
        "errorMissingAddress": "Mae angen cyfeiriad i adnabod yr adeilad",
        "errorMissingCategory": "Mae angen categori i helpu eraill i wybod beth i'w ddisgwyl",
        "errorInvalidPostcode": "Os cyflenwir cod post rhaid iddo fod yn ddilys, neu ddefnyddio'r cyfesurynnau yn unig",
        "errorInvalidCoordinates": "Gellir gosod cyfesurynnau trwy symud y pin ar y map ac mae eu hangen",
        "errorInvalidCategory": "Rhaid gosod y categori",
        "errorCoordinatesMismatch": "Ni fu'n bosibl gwirio'r cyfesurynnau a gyflenwir, ceisiwch eto",
        "privacyType": "Math",
        "privacyLink": "Dolen lawrlwytho",
        "privacySHA256": "Stwnsh SHA256"
    },
    "english": {
        "pageTitleKeyHome": "Home",
        "pageTitleKeyMap": "Map",
        "pageTitleKeyVocabulary": "Vocab",
        "pageTitleKeyAbout": "About",
        "pageTitleKeySubmit": "Submit",
        "pageTitleKeyPrivacy": "Privacy",
        "pageTitleTagKeyHome": "BYW | Home",
        "pageTitleTagKeyMap": "BYW | Map",
        "pageTitleTagKeyVocabulary": "BYW | Vocab",
        "pageTitleTagKeyAbout": "BYW | About",
        "pageTitleTagKeySubmit": "BYW | Submit",
        "pageTitleTagKeyPrivacy": "BYW | Privacy",
        "pageTitleTagKey404": "BYW | Page Not Found",
        "footerTest404": "Test the 404 page",
        "footerContributing": "Contributing",
        "footerP1": "Everyone can help learners find places to go and use their Welsh. Your submissions also help us to monitor how much the language is used, not just in Wales, but across the world",
        "footerP2": "Submitting a review is quick and no account or login is required. If you are aware of a place that Welsh can be heard and used, but is not already in our index, submitting it to the index will let others know",
        "footerUsefulLinks": "Useful links",
        "footerVisitOn": "Visit us on",
        "category0": "Highly unlikely",
        "category1": "Not very likely",
        "category2": "Likely",
        "category3": "Very likely",
        "category4": "Highly likely",
        "category5": "Definitely",
        "show": "Show",
        "categorise": "Categorise",
        "notFoundTitle": "404 Not Found",
        "homeCrowdSourced": "Crowd sourced",
        "homeWelsh": "Welsh",
        "homeLanguageResource": "language resource",
        "homeLets": "Let's",
        "homeFind": "find",
        "homeSomewhere": "somewhere",
        "homeHeroTitle": "Find out where to use and hear the language",
        "homeSearch": "Search",
        "homeSearchPlaceholder": "What are you searching for?",
        "homeSearchResults": "Search Results",
        "homeLocationPlaceholder": "Location",
        "homeAnd": "and",
        "homeMore": "more",
        "homeApi": "API",
        "homeMap": "Map",
        "homeLanguages": "Languages",
        "homeLanguageChoose": "Choose your preferred language",
        "homeServicesSectionTitle": "Our Services",
        "homeServicesSectionTitle1": "What does",
        "homeServicesSectionTitle2": "do for me?",
        "homeServices1Title": "Local Places",
        "homeServices1Desc": "This site is simply about getting people to use their Welsh. It is available in a couple of languages to help learners from all parts of the globe to find places to use and improve their Welsh skills",
        "homeServices2Title": "Native Speakers",
        "homeServices2Desc": "However, this is not just about learners. Those fluent need to also use their Welsh whenever they can. Welsh needs to be heard on the street, in the shops and wherever we get together",
        "homeServices3Title": "Days out",
        "homeServices3Desc": "So, before you shop, go on a day out, or whatever you like to do, see if there will be a Welsh language welcome and, above all, use your Welsh yourself!",
        "homeThoughtOfTheDay": "Thought of the day",
        "mapResult": "Result",
        "mapResults": "Results",
        "mapPages": "Pages",
        "mapSearchPlaceholder": "Search for places, coordinates and postcodes",
        "mapLegendTitle": "Legend to the map",
        "mapLegendSubheading": "A quick glympse of Welsh speaking likeliness",
        "vocabTitle": "Vocabulary",
        "vocabBeta": "Beta",
        "vocabP1": "This is a beta version of an attempt to provide a searchable resource for commonly heard sayings",
        "vocabP2": "Currently it has",
        "vocabP3": "words and phrases out of a target of",
        "vocabResultsFound": "phrases and words found",
        "vocabEnglish": "English",
        "vocabCymraeg": "Cymraeg",
        "vocabNotes": "Notes",
        "aboutTitle": "About",
        "aboutSub1": "What can",
        "aboutSub2": "do?",
        "aboutP1": "Byw.cymru is a community driven, crowd sourced, Welsh language resource. Its primary aim is to help learners and others who are interested in the language find places where they can hear and use the language",
        "aboutP2a": "The whole project is",
        "aboutOpenSource": "open source",
        "aboutP2b": "and all decisions are made in the open on the projects repo, hosted on",
        "aboutP3": "The aim of the project is to make finding out this information as easy as possible, with the maximum of community involvement. Therefore the design of the website is to be as easy and quick to use as possible. It is focused around the map page which is the primary resource for searching the index",
        "aboutP4": "All the code that makes up the website is available in the projects repo and is viewable by anybody. The website and data is hosted using community donated resources. The Api provides access to the data to anybody who wants it. Over time it is expected that the number of Api endpoints will be increased to make it more useful to developers and researchers",
        "aboutContributing": "Contributing",
        "aboutP5": "The quickest and easiest way to contribute to the project is to submit a review. This just means adding a new place to the index or updating an existing one if necessary",
        "aboutP6": "Anybody can do this and no login or account is necessary",
        "aboutP7a": "If there are any issues discovered, bugs found or suggestions to be made then check out the",
        "aboutP7b": "issues page",
        "aboutP7c": "on",
        "aboutP8": "Those who wish to be more involved should check out the project repo, which is hosted on",
        "aboutP9": "There is plenty of work to do to make this project a useful tool for Welsh learners",
        "submitTitle": "Submit a categorisation",
        "submitName": "Name",
        "submitCategory": "Category",
        "submitStatus": "Status",
        "howToTitle": "How to",
        "howToFind": "find somewhere already listed",
        "howToOL1a": "The premises you selected in the map page will appear in the submit box ready for your review of Welsh speaking likelyhood",
        "howToOL1b": "Choose what you feel is best and hit submit",
        "howToOL1c": "If the premises you selected is not where you want to submit a review for then just drag the map pin, the form will be cleared, and you can locate the premises you want to submit",
        "howToSubmit": "submit a new premises",
        "howToOL2a": "Drag the map pin to locate the place",
        "howToOL2b": "The coordinates and postcode will be filled out. Just add the name of the premises and the address as you would like it to appear in the index",
        "howToOL2c": "Select how likely you feel a person is to hear and be able to use Welsh in the premises. This isn't scientific, just what you think is likely",
        "howToInaccurate": "If the index appears inaccurate",
        "howToP1": "The category (how likely it is to use Welsh) of a premises is calculated by aggregating all the reviews received. So your submission will be taken into account straight away, but it may or may not affect the current rating",
        "howToP2": "If you feel the rating of a premises is way off and remains way off after you have submitted your rating, then please get in touch. If you are the business owner we can help by pointing you in the direction of resources to help increase the use of Welsh in your business. If the data in the index is just plain wrong then we can correct it",
        "formSubmitted": "Submitted",
        "formSubmit": "Submit",
        "formClear": "Clear",
        "formClearToDrop": "Clear the form to drop a pin",
        "formDragPin": "Drag the pin...",
        "formName": "Name of premises",
        "formAddress": "Address of premises",
        "formPostcode": "Postcode of premises",
        "formCoordinates": "Coordinates",
        "formCategory": "Category",
        "errorMissingName": "A name is required",
        "errorMissingAddress": "An address is required to identify the premises",
        "errorMissingCategory": "A category is required to help others know what to expect",
        "errorInvalidPostcode": "If a postcode is supplied it must be valid, or just use the coordinates",
        "errorInvalidCoordinates": "Coordinates can be set by moving the pin on the map and are required",
        "errorInvalidCategory": "The category has to be set",
        "errorCoordinatesMismatch": "It has not been possible to verify the supplied coordinates, please try again",
        "privacyType": "Type",
        "privacyLink": "Download link",
        "privacySHA256": "SHA256 Hash"
    },
    "español": {
        "pageTitleKeyHome": "Página principal",
        "pageTitleKeyMap": "Mapa",
        "pageTitleKeyVocabulary": "Vocabulario en galés",
        "pageTitleKeyAbout": "Acerca de BYW",
        "pageTitleKeySubmit": "Añadir ubicaciones a este mapa",
        "pageTitleKeyPrivacy": "Privacidad",
        "pageTitleTagKeyHome": "BYW | Página principal",
        "pageTitleTagKeyMap": "BYW | Mapa",
        "pageTitleTagKeyVocabulary": "BYW | Vocabulario en galés",
        "pageTitleTagKeyAbout": "BYW | Acerca de BYW",
        "pageTitleTagKeySubmit": "BYW | Añadir ubicaciones a este mapa",
        "pageTitleTagKeyPrivacy": "BYW | Privacidad",
        "pageTitleTagKey404": "BYW | No se pudo encontrar la página",
        "footerTest404": "Probar la página de error 404",
        "footerContributing": "¿Cómo puedo contribuir?",
        "footerP1": "Todo el mundo puede ayudar a los que están aprendiendo galés a encontrar lugares donde se puede practicar el galés. Además de ayudar a estudiantes del galés, sus contribuciones nos ayudan a comprobar cuanto se usa el idioma galés, no solo en Galés, sino por todo el mundo.",
        "footerP2": "Escribirnos una reseña sobre el uso del galés en un lugar es rápido y no se requiere crear una cuenta para hacerlo. Si conoce a un lugar de habla galesa, que no se haya añadido a nuestro indíce de lugares, añadirlo al indíce imformará a más personas.",
        "footerUsefulLinks": "Enlaces útiles",
        "footerVisitOn": "Contáctenos por",
        "category0": "Muy improbable",
        "category1": "No muy probable",
        "category2": "Probable",
        "category3": "Muy probable",
        "category4": "Muy probable",
        "category5": "Definitivamente",
        "show": "Mostrar ubicación en la mapa",
        "categorise": "Clasificar por categorías",
        "notFoundTitle": "404 No se pudo encontrar la página",
        "homeCrowdSourced": "Un recurso del idioma",
        "homeWelsh": "galés",
        "homeLanguageResource": "impulsado por la gente",
        "homeLets": "Encontremos",
        "homeFind": "un",
        "homeSomewhere": "lugar",
        "homeHeroTitle": "Descubra lugares de habla galesa",
        "homeSearch": "Buscar",
        "homeSearchPlaceholder": "¿Qué está buscando?",
        "homeSearchResults": "Resultados de la búsqueda",
        "homeLocationPlaceholder": "Ubicación",
        "homeAnd": "y",
        "homeMore": "más",
        "homeApi": "API",
        "homeMap": "Mapa",
        "homeLanguages": "Idiomas",
        "homeLanguageChoose": "Elija su idioma preferido",
        "homeServicesSectionTitle": "Nuestros servicios",
        "homeServicesSectionTitle1": "¿Que hace",
        "homeServicesSectionTitle2": "para mí?",
        "homeServices1Title": "Lugares locales",
        "homeServices1Desc": "Este sitio trata simplemente de hacer que la gente use su galés. Está disponible en un par de idiomas para ayudar a los estudiantes de todas partes del mundo a encontrar lugares para usar y mejorar sus habilidades de galés.",
        "homeServices2Title": "Hablantes nativos",
        "homeServices2Desc": "Sin embargo, este proyecto no se trata solo de estudiantes. Aquellos que lo dominan también deben usar su galés cuandoquiera que puedan. Se debe poder escuchar el galés en la calle, en las tiendas y dondequiera que nos reunamos",
        "homeServices3Title": "Días libres",
        "homeServices3Desc": "Entonces, antes de que vaya de compras o vaya de excursión o lo que sea que le guste hacer, vea si se te dará la bienvenida galesa y, sobre todo ¡Recuerde usar su galés!",
        "homeThoughtOfTheDay": "El pensamiento del día",
        "mapResult": "Resultado",
        "mapResults": "Resultados",
        "mapPages": "Paginas",
        "mapSearchPlaceholder": "Buscar por lugares, coordenadas y códigos postales.",
        "mapLegendTitle": "Leyenda del mapa",
        "mapLegendSubheading": "Un resumen corto de la probabilidad de que se use el galés en un establecimiento",
        "vocabTitle": "Vocabulario en galés",
        "vocabBeta": "Beta",
        "vocabP1": "Esta página es un intento de proveer un diccionario de frases comunes en el galés que todavía está en fase Beta.",
        "vocabP2": "Actualmente contiene",
        "vocabP3": "palabras y frases de un objetivo de",
        "vocabResultsFound": "frases y palabras encontradas",
        "vocabEnglish": "inglés (aún no está disponible en español)",
        "vocabCymraeg": "Galés",
        "vocabNotes": "Notas",
        "aboutTitle": "Sobre",
        "aboutSub1": "¿Qué puede hacer",
        "aboutSub2": "?",
        "aboutP1": "Byw.cymru es un recurso del idioma galés impulsado por la comunidad y de origen colectivo. Su propósito principal es ayudar a los estudiantes y a otras personas interesadas en el idioma a encontrar lugares donde puedan escuchar y usar el idioma.",
        "aboutP2a": "Todo el proyecto es",
        "aboutOpenSource": "de código abierto",
        "aboutP2b": "y todas las decisiones se toman públicamente en el repositorio del proyecto, en",
        "aboutP3": "El objetivo del proyecto es hacer que la búsqueda de esta información sobre el galés sea tan fácil como posible, con la participación máxima de la comunidad. Por lo tanto, el diseño del sitio web debe ser lo más fácil y rápido de usar posible. Se centra en la página del mapa, que es el recurso principal para buscar en el índice.",
        "aboutP4": "Todo el código del que se compone el sitio web está disponible en el repositorio de proyectos y cualquiera persona puede verlo. El sitio web y los datos se almacenan por utilizar recursos donados por la comunidad. La API le proporciona acceso a estos datos a cualquiera persona que lo desee. Con el tiempo, se espera que la cantidad de puntos finales Api aumente para que sea más útil para desarrolladores e investigadores.",
        "aboutContributing": "¿Cómo puedo contribuir?",
        "aboutP5": "La forma más rápida y sencilla de contribuir al proyecto es escribir una reseña. Esto solo significa añadir un nuevo lugar al índice o actualizar datos sobre un lugar que ya se ha añadido si es necesario",
        "aboutP6": "Todo el mundo puede hacer esto y no requiere que crea una cuenta.",
        "aboutP7a": "Si se descubren problemas, errores o si tiene algunas sugerencias, consulte el",
        "aboutP7b": "página de problemas",
        "aboutP7c": "en",
        "aboutP8": "Aquellos que deseen participar más deben consultar el repositorio del proyecto, que se encuentra en",
        "aboutP9": "Hay mucho trabajo que hacer para que este proyecto sea una herramienta útil para los estudiantes del galés.",
        "submitTitle": "Añadir una categorización",
        "submitName": "Nombre",
        "submitCategory": "Categoría",
        "submitStatus": "Estado",
        "howToTitle": "Cómo puedo",
        "howToFind": "encontrar un establecimiento que ya está en la lista",
        "howToOL1a": "El establecimiento que seleccionó en la página del mapa aparecerá en el cuadro de adición listo para su reseña de la probabilidad de que se use el galés",
        "howToOL1b": "Elija la opción que crea sea mejor y haga clic en 'Añadir'",
        "howToOL1c": "Si el establecimiento que seleccionó no está en el lugar donde desea añadir una reseña, simplemente arrastre la chincheta del mapa, el formulario se borrará y podrá ubicar el establecimiento que desea añadir al mapa.",
        "howToSubmit": "añadir ubicaciones nuevas a este mapa",
        "howToOL2a": "Arrastre la chincheta del mapa para ubicar el establecimiento",
        "howToOL2b": "Se completarán las coordenadas y el código postal. Simplemente agregue el nombre del establecimiento y la dirección como le gustaría que aparezca en el índice",
        "howToOL2c": "Seleccione que tan probable cree que es que alguien oiga y que pueda practicar el galés en el establecimiento. Esto no tiene que ser una evaluación científica, solamente tiene que representar lo que cree que es probable.",
        "howToInaccurate": "Si la categoría de un establecimiento en el índice parece inexacto",
        "howToP1": "La categoría (la probabilidad de que se use galés) de un establecimiento se calcula por sumir todas las reseñas, por lo que se recibirá su reseña tan pronto como la haya escrito, pero no necesariamente afectará a la categoría del establecimiento en la actualidad.",
        "howToP2": "Si cree que la categoría de un establecimiento es muy inexacto y queda sin cambiar despues de que haya añadido su reseña, por favor póngase en contacto con nosotros. Si usted es el propietario de esta empresa, podemos ayudarlo indicándole la dirección de los recursos que le ayudarán a aumentar el uso del galés en su empresa. Si los datos del índice son simplemente incorrectos, podemos corregirlos.",
        "formSubmitted": "Se añadió su contribución",
        "formSubmit": "Añadir",
        "formClear": "Borrar",
        "formClearToDrop": "Borre el formulario para colocar la chincheta",
        "formDragPin": "Arrastrar la chincheta ...",
        "formName": "Nombre del establecimiento",
        "formAddress": "Dirección del establecimiento",
        "formPostcode": "Código postal del establecimiento",
        "formCoordinates": "Coordenadas",
        "formCategory": "Categoría",
        "errorMissingName": "Se requiere un nombre",
        "errorMissingAddress": "Se requiere una dirección para identificar el establecimiento.",
        "errorMissingCategory": "Se requiere una categoría para ayudar a otras personas a saber qué deberían esperar",
        "errorInvalidPostcode": "Si se proporciona un código postal, debe ser válido, o simplemente use las coordenadas del establecimiento",
        "errorInvalidCoordinates": "Las coordenadas se pueden establecer por arrastrar la chincheta en el mapa y son obligatorias",
        "errorInvalidCategory": "La categoría tiene que estar seleccionada",
        "errorCoordinatesMismatch": "No nos ha resultado posible verificar las coordenadas proporcionadas. Vuelva a intentarlo.",
        "privacyType": "Escribir",
        "privacyLink": "Enlace de descarga",
        "privacySHA256": "Hash SHA256"
    },
    "italiano": {
        "pageTitleKeyHome": "Casa",
        "pageTitleKeyMap": "Carta geografica",
        "pageTitleKeyVocabulary": "Vocab",
        "pageTitleKeyAbout": "Di",
        "pageTitleKeySubmit": "Invia",
        "pageTitleKeyPrivacy": "Privacy",
        "pageTitleTagKeyHome": "BYW | Casa",
        "pageTitleTagKeyMap": "BYW | Carta geografica",
        "pageTitleTagKeyVocabulary": "BYW | Vocab",
        "pageTitleTagKeyAbout": "BYW | Di",
        "pageTitleTagKeySubmit": "BYW | Invia",
        "pageTitleTagKeyPrivacy": "BYW | Privacy",
        "pageTitleTagKey404": "BYW | Pagina non trovata",
        "footerTest404": "Prova la pagina 404",
        "footerContributing": "Contribuire",
        "footerP1": "Tutti possono aiutare gli studenti a trovare posti dove andare e utilizzare il loro gallese. I tuoi contributi ci aiutano anche a monitorare quanto la lingua viene utilizzata, non solo in Galles, ma in tutto il mondo",
        "footerP2": "L'invio di una recensione è veloce e non è richiesto alcun account o accesso. Se sei a conoscenza di un luogo in cui il gallese può essere ascoltato e utilizzato, ma non è già nel nostro indice, inviarlo all'indice ne informerà gli altri",
        "footerUsefulLinks": "Link utili",
        "footerVisitOn": "Venite a trovarci su",
        "category0": "Altamente improbabile",
        "category1": "Non molto probabile",
        "category2": "Probabile",
        "category3": "Molto probabilmente",
        "category4": "Molto probabile",
        "category5": "Decisamente",
        "show": "Spettacolo",
        "categorise": "Classificare",
        "notFoundTitle": "404 non trovato",
        "homeCrowdSourced": "Folla di provenienza",
        "homeWelsh": "Gallese",
        "homeLanguageResource": "Risorsa linguistica",
        "homeLets": "Andiamo",
        "homeFind": "trova",
        "homeSomewhere": "da qualche parte",
        "homeHeroTitle": "Scopri dove usare e ascolta la lingua",
        "homeSearch": "Ricerca",
        "homeSearchPlaceholder": "Che cosa stai cercando?",
        "homeSearchResults": "risultati di ricerca",
        "homeLocationPlaceholder": "Posizione",
        "homeAnd": "e",
        "homeMore": "di più",
        "homeApi": "API",
        "homeMap": "Carta geografica",
        "homeLanguages": "Le lingue",
        "homeLanguageChoose": "Scegli la tua lingua preferita",
        "homeServicesSectionTitle": "I nostri servizi",
        "homeServicesSectionTitle1": "Cosa fa",
        "homeServicesSectionTitle2": "fare per me?",
        "homeServices1Title": "Luoghi locali",
        "homeServices1Desc": "Questo sito serve semplicemente a convincere le persone a usare il loro gallese. È disponibile in un paio di lingue per aiutare gli studenti di tutte le parti del mondo a trovare luoghi da utilizzare e migliorare le loro abilità gallesi",
        "homeServices2Title": "Madrelingua",
        "homeServices2Desc": "Tuttavia, non si tratta solo di studenti. Quelli fluenti devono anche usare il loro gallese ogni volta che possono. Il gallese ha bisogno di essere ascoltato per strada, nei negozi e ovunque ci incontriamo",
        "homeServices3Title": "Giorni fuori",
        "homeServices3Desc": "Quindi, prima di fare acquisti, esci una giornata, o qualunque cosa ti piaccia fare, vedi se ci sarà un benvenuto in lingua gallese e, soprattutto, usa tu stesso il tuo gallese!",
        "homeThoughtOfTheDay": "Pensiero del giorno",
        "mapResult": "Risultato",
        "mapResults": "Risultati",
        "mapPages": "Pages",
        "mapSearchPlaceholder": "Cerca luoghi, coordinate e codici postali",
        "mapLegendTitle": "Legenda alla mappa",
        "mapLegendSubheading": "Un rapido lampo di verosimiglianza di lingua gallese",
        "vocabTitle": "Vocabolario",
        "vocabBeta": "Beta",
        "vocabP1": "Questa è una versione beta di un tentativo di fornire una risorsa ricercabile per detti comunemente ascoltati",
        "vocabP2": "Attualmente lo ha",
        "vocabP3": "parole e frasi fuori da un obiettivo di",
        "vocabResultsFound": "frasi e parole trovate",
        "vocabEnglish": "Inglese",
        "vocabCymraeg": "Cymraeg",
        "vocabNotes": "Appunti",
        "aboutTitle": "Di",
        "aboutSub1": "Cosa può",
        "aboutSub2": "fare?",
        "aboutP1": "Byw.cymru è una risorsa in lingua gallese guidata dalla comunità e raccolta in crowdsourcing. Il suo scopo principale è aiutare gli studenti e gli altri interessati alla lingua a trovare luoghi in cui possono ascoltare e usare la lingua",
        "aboutP2a": "L'intero progetto è",
        "aboutOpenSource": "open source",
        "aboutP2b": "e tutte le decisioni vengono prese all'aperto nel repository dei progetti, ospitato su",
        "aboutP3": "Lo scopo del progetto è rendere la ricerca di queste informazioni il più semplice possibile, con il massimo coinvolgimento della comunità. Pertanto il design del sito web deve essere il più facile e veloce possibile da usare. Si concentra sulla pagina della mappa che è la risorsa principale per la ricerca nell'indice",
        "aboutP4": "Tutto il codice che compone il sito web è disponibile nel repository dei progetti ed è visualizzabile da chiunque. Il sito Web e i dati sono ospitati utilizzando risorse donate dalla comunità. L'API fornisce l'accesso ai dati a chiunque lo desideri. Nel tempo si prevede che il numero di endpoint API aumenterà per renderlo più utile per sviluppatori e ricercatori",
        "aboutContributing": "Contribuire",
        "aboutP5": "Il modo più rapido e semplice per contribuire al progetto è inviare una recensione. Ciò significa semplicemente aggiungere una nuova posizione all'indice o aggiornarne una esistente, se necessario",
        "aboutP6": "Chiunque può farlo e non è necessario alcun login o account",
        "aboutP7a": "Se vengono rilevati problemi, bug rilevati o suggerimenti da fornire, controllare il file",
        "aboutP7b": "pagina dei problemi",
        "aboutP7c": "su",
        "aboutP8": "Coloro che desiderano essere più coinvolti dovrebbero controllare il repository del progetto, che è ospitato su",
        "aboutP9": "C'è molto lavoro da fare per rendere questo progetto uno strumento utile per gli studenti gallesi",
        "submitTitle": "Invia una classificazione",
        "submitName": "Nome",
        "submitCategory": "Categoria",
        "submitStatus": "Stato",
        "howToTitle": "Come",
        "howToFind": "trova un posto già elencato",
        "howToOL1a": "I locali che hai selezionato nella pagina della mappa appariranno nella casella di invio pronti per la tua revisione della probabilità di parlare gallese",
        "howToOL1b": "Scegli ciò che ritieni sia migliore e premi Invia",
        "howToOL1c": "Se i locali che hai selezionato non sono quelli per i quali desideri inviare una recensione, trascina semplicemente il segnaposto della mappa, il modulo verrà cancellato e potrai individuare i locali che desideri inviare",
        "howToSubmit": "presentare una nuova sede",
        "howToOL2a": "Trascina il segnaposto della mappa per individuare il luogo",
        "howToOL2b": "Le coordinate e il codice postale verranno inseriti. Basta aggiungere il nome dei locali e l'indirizzo come vorresti che appaia nell'indice",
        "howToOL2c": "Seleziona la probabilità che una persona senta e sia in grado di usare il gallese nei locali. Questo non è scientifico, solo quello che pensi sia probabile",
        "howToInaccurate": "Se l'indice appare impreciso",
        "howToP1": "La categoria (quanto è probabile che utilizzi il gallese) di un locale viene calcolata aggregando tutte le recensioni ricevute. Quindi la tua richiesta verrà presa in considerazione immediatamente, ma potrebbe o meno influenzare la valutazione attuale",
        "howToP2": "Se ritieni che la valutazione di un locale sia lontana e rimanga lontana dopo aver inviato la tua valutazione, contattaci. Se sei il titolare dell'attività, possiamo aiutarti indicandoti le risorse per aumentare l'uso del gallese nella tua attività. Se i dati nell'indice sono semplicemente sbagliati, possiamo correggerli",
        "formSubmitted": "Inviato",
        "formSubmit": "Invia",
        "formClear": "Chiaro",
        "formClearToDrop": "Cancella il modulo per inserire un segnaposto",
        "formDragPin": "Trascina il segnaposto...",
        "formName": "Nome dei locali",
        "formAddress": "Indirizzo dei locali",
        "formPostcode": "Codice postale dei locali",
        "formCoordinates": "Coordinate",
        "formCategory": "Categoria",
        "errorMissingName": "È richiesto un nome",
        "errorMissingAddress": "È necessario un indirizzo per identificare i locali",
        "errorMissingCategory": "È necessaria una categoria per aiutare gli altri a sapere cosa aspettarsi",
        "errorInvalidPostcode": "Se viene fornito un codice postale, deve essere valido o utilizzare semplicemente le coordinate",
        "errorInvalidCoordinates": "Le coordinate possono essere impostate spostando il segnaposto sulla mappa e sono obbligatorie",
        "errorInvalidCategory": "La categoria deve essere impostata",
        "errorCoordinatesMismatch": "Non è stato possibile verificare le coordinate fornite, riprova",
        "privacyType": "Genere",
        "privacyLink": "Link per scaricare",
        "privacySHA256": "SHA256 Hash"
    }
};
