// This file is created by the build system and should not be manually edited or changes
// will be lost.

// It is created to allow for code completion of the supported keys to access the page
// text translations. Its prescence assists the page component author to locate the relevant
// piece of user facing text. It also means that components that attempt to access none
// existing keys will be found at build time, rather than runtime.

export default {
    pageTitleKeyHome: "pageTitleKeyHome", 
    pageTitleKeyMap: "pageTitleKeyMap", 
    pageTitleKeyVocabulary: "pageTitleKeyVocabulary", 
    pageTitleKeyAbout: "pageTitleKeyAbout", 
    pageTitleKeySubmit: "pageTitleKeySubmit", 
    pageTitleKeyPrivacy: "pageTitleKeyPrivacy", 
    pageTitleTagKeyHome: "pageTitleTagKeyHome", 
    pageTitleTagKeyMap: "pageTitleTagKeyMap", 
    pageTitleTagKeyVocabulary: "pageTitleTagKeyVocabulary", 
    pageTitleTagKeyAbout: "pageTitleTagKeyAbout", 
    pageTitleTagKeySubmit: "pageTitleTagKeySubmit", 
    pageTitleTagKeyPrivacy: "pageTitleTagKeyPrivacy", 
    pageTitleTagKey404: "pageTitleTagKey404", 
    footerTest404: "footerTest404", 
    footerContributing: "footerContributing", 
    footerP1: "footerP1", 
    footerP2: "footerP2", 
    footerUsefulLinks: "footerUsefulLinks", 
    footerVisitOn: "footerVisitOn", 
    category0: "category0", 
    category1: "category1", 
    category2: "category2", 
    category3: "category3", 
    category4: "category4", 
    category5: "category5", 
    show: "show", 
    categorise: "categorise", 
    homeCrowdSourced: "homeCrowdSourced", 
    homeWelsh: "homeWelsh", 
    homeLanguageResource: "homeLanguageResource", 
    homeLets: "homeLets", 
    homeFind: "homeFind", 
    homeSomewhere: "homeSomewhere", 
    homeHeroTitle: "homeHeroTitle", 
    homeSearch: "homeSearch", 
    homeSearchPlaceholder: "homeSearchPlaceholder", 
    homeSearchResults: "homeSearchResults", 
    homeLocationPlaceholder: "homeLocationPlaceholder", 
    homeAnd: "homeAnd", 
    homeMore: "homeMore", 
    homeApi: "homeApi", 
    homeMap: "homeMap", 
    homeServicesSectionTitle: "homeServicesSectionTitle", 
    homeServicesSectionTitle1: "homeServicesSectionTitle1", 
    homeServicesSectionTitle2: "homeServicesSectionTitle2", 
    homeServices1Title: "homeServices1Title", 
    homeServices1Desc: "homeServices1Desc", 
    homeServices2Title: "homeServices2Title", 
    homeServices2Desc: "homeServices2Desc", 
    homeServices3Title: "homeServices3Title", 
    homeServices3Desc: "homeServices3Desc", 
    homeThoughtOfTheDay: "homeThoughtOfTheDay", 
    mapResult: "mapResult", 
    mapResults: "mapResults", 
    mapPages: "mapPages", 
    mapSearchPlaceholder: "mapSearchPlaceholder", 
    mapLegendTitle: "mapLegendTitle", 
    mapLegendSubheading: "mapLegendSubheading"
};
